version: '3.8'

services:
  web:
    build: .
    ports:
      - "${PORT:-5001}:5001"
    environment:
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-password}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - JELLYFIN_TOKEN=${JELLYFIN_TOKEN}
      - JELLYFIN_HOST=${JELLYFIN_HOST}
      - SITE_TITLE=${SITE_TITLE:-Zurg Suite}
      - SITE_LOGO_PATH=${SITE_LOGO_PATH:-static/zs.png}
      - SITE_FAVICON_PATH=${SITE_FAVICON_PATH:-static/favicon.ico}
      - ZURG_HOST=${ZURG_HOST}
      - SCHEDULE_JELLYFIN_DAILY_ACTION=${SCHEDULE_JELLYFIN_DAILY_ACTION}
      - SCHEDULE_JELLYFIN_DAILY_CRON=${SCHEDULE_JELLYFIN_DAILY_CRON}
      - SCHEDULE_JELLYFIN_DAILY_ENABLED=${SCHEDULE_JELLYFIN_DAILY_ENABLED}
      - SCHEDULE_WORKER_WEEKLY_ACTION=${SCHEDULE_WORKER_WEEKLY_ACTION}
      - SCHEDULE_WORKER_WEEKLY_CRON=${SCHEDULE_WORKER_WEEKLY_CRON}
      - SCHEDULE_WORKER_WEEKLY_ENABLED=${SCHEDULE_WORKER_WEEKLY_ENABLED}
      - SCHEDULE_REMOUNT_ACTION=${SCHEDULE_REMOUNT_ACTION}
      - SCHEDULE_REMOUNT_CRON=${SCHEDULE_REMOUNT_CRON}
      - SCHEDULE_REMOUNT_ENABLED=${SCHEDULE_REMOUNT_ENABLED}
    volumes:
      - ./static:/app/static
    restart: unless-stopped 